tmpPath: './temp'
archivePath: './archive'
# oss:  # 存储到OSS
#   url: "http://oss-cn-hangzhou.aliyuncs.com"
#   bucket: "jfjun4test"
#   accessKey: "accessKey"
#   secretKey: "secretKey"
#   prefix: 'backup/'  # oss中的存储根路径
#   # 存储策略，只有一个起作用，优先级timeDecay>retention>expireDays，
#   expireDays: 730  # 最大保存天数
#   retention: 14    # 最大保留分数
#   timeDecay:
#     - months: 6 # 如果超过2个月后，每个月只保留一份
#     - years: 10 # 如果超过2年后，每年只保留一份
#     - days: 6
#     - weeks: 3

# 存放到本地,存放目录 {archivePath}/{task.name}/
local:
  # 稀疏策略，如果配置了稀疏策略，则retention失效，expireDays失效
  expireDays: 730  # 最大保存天数
  retention: 10    # 最大保留份数
  timeDecay:   # 时间衰减保存策略
    days: 6   # 最近6天，每天保存一份
    weeks: 3  # 最近3周，每周保存一份
    months: 6 # 最近6个月，每月保存一份
    years: 5  # 最近5年，每年保存一份，超过5年以上就不保留备份了

tasks:
  - name: 'mysql1'
    type: 'mysql'
    schedule: "day 14:00"  # 每周
    params:  # 通过mysqldumap执行的参数
      # uri: "mysql://root:123456@127.0.0.1/db1"
      u: "root"
      p: "vte_m"
      P: 3308
      databases: "guns_advanced"
      host: "192.168.208.1"
  - name: 'mongo1'
    type: 'mongodb'
    schedule: "day 13:15" # 每天 13:15执行
    params:  # 通过mongodump执行的参数
      # uri: "mongodb://test:test@127.0.0.1:13722/lcz_test1"
      authenticationDatabase: admin
      d: dictionary
      u: root
      p: Aaxywy123
      h: 19.16.13.92:8017
